### ISSUE TITLE
serve app via github pages

### ISSUE THREAD

**Issue by csae8092** [kaggl/Assessment-Task#1]
without any proper research I think it should be straight forward to publish the appliction via Github pages
ideally all you need to do is to check in the build folder and point to this folder in the github-pages section in the settings
even nicer would it be if you don't check in the build folder but letting the build run via github-actions

some quick googling https://medium.com/@mrjohnkilonzi/how-to-deploy-your-vuejs-using-github-actions-on-firebase-hosting-a667aabd88f7

**Comment by kaggl** [comment]
Done!

Github-Pages checks out the gh-pages branch, which is just the dist folder of my Dev Branch as a subtree

check it out here: https://kaggl.github.io/Assessment-Task/

to do this, i followed this handy guide: https://learnvue.co/2020/09/how-to-deploy-your-vue-app-to-github-pages/
