### ISSUE TITLE
basic network-visualisation

### ISSUE THREAD

**Issue by csae8092** [kaggl/Assessment-Task#7]
https://mmp.acdh-dev.oeaw.ac.at/archiv/keyword-data/ 
* returns graph-data following the data format required from https://github.com/acdh-oeaw/network-visualization
* takes the same query-params as https://mmp.acdh-dev.oeaw.ac.at/archiv/keyword/ so you can use the gui-interface to get yourself acquainted with the API

use this endpoint to set up a basic network visualisation of the returned data
* be aware that the API only returns something if the number of selected nodes is smaller than 70; so for testing you can use a query like this on https://mmp.acdh-dev.oeaw.ac.at/archiv/keyword-data/?rvn_stelle_key_word_keyword__text__autor__ort=87 (give me all keywords related to a text written by an author related to Spain)

users should be able to
* filter/search Keywords by 'Stichwort' (fuzzy search)
* type of the keyword (select between the two existing options or take all)
* the related author (multi-select of options suggested via autocomplete)

but feel free to add more filters as you like

**Comment by csae8092** [comment]
the  main idea of this task is that you get familiar with https://github.com/acdh-oeaw/network-visualization

**Comment by kaggl** [comment]
Every functionaly has been implemented now with commit 3c8e61de1a72f2c7ac6e70c5fa977135b0e326a6
